sentence = input("Enter a sentence : ")
cleaned_sentence = sentence.lower().strip()
words_list = cleaned_sentence.split()
total_word = len(words_list)
total_characters = len(cleaned_sentence)
unique_words = set(words_list)
total_unique_words = len(unique_words)
print("----- Text Analysis Summary -----")
print("Cleaned text: ", cleaned_sentence)
print("Total characters: ", total_characters)
print("Total words: ", total_word)
print("Unique words: ",total_unique_words)
print("--------------------------------")